create_clock -name {I_clk} -period 40.000 -waveform {0.000 20.000} [get_ports {I_clk}] -add
create_clock -name {rx_reclk_e} -period 10.000 -waveform {0.000 5.000} [get_ports {I_lvds_rx_clk_e}]
create_clock -name {rx_reclk_o} -period 10.000 -waveform {0.000 5.000} [get_ports {I_lvds_rx_clk_o}]
derive_clocks
rename_clock -name {rx_clk_e_out0} [get_clocks {u_rx_pll_even/u_rx_pll/PH1P_PHY_PLL_WRAPPER_393d45aa68c4_Inst/u_PH1P_PHY_PLL.clkc[0]}]
rename_clock -name {rx_clk_e_out1} [get_clocks {u_rx_pll_even/u_rx_pll/PH1P_PHY_PLL_WRAPPER_393d45aa68c4_Inst/u_PH1P_PHY_PLL.clkc[1]}]
rename_clock -name {rx_clk_o_out0} [get_clocks {u_rx_pll_odd/u_rx_pll/PH1P_PHY_PLL_WRAPPER_393d45aa68c4_Inst/u_PH1P_PHY_PLL.clkc[0]}]
rename_clock -name {rx_clk_o_out1} [get_clocks {u_rx_pll_odd/u_rx_pll/PH1P_PHY_PLL_WRAPPER_393d45aa68c4_Inst/u_PH1P_PHY_PLL.clkc[1]}]
rename_clock -name {tx_clk_e_out0} [get_clocks {u_tx_pll_even/u_tpll/ph1p_phy_pll_wrapper_d8cf02616d56_Inst/u_PH1P_PHY_PLL.clkc[0]}]
rename_clock -name {tx_clk_o_out0} [get_clocks {u_tx_pll_odd/u_tpll/ph1p_phy_pll_wrapper_d8cf02616d56_Inst/u_PH1P_PHY_PLL.clkc[0]}]
rename_clock -name {tx_clk_o_out1} [get_clocks {u_tx_pll_odd/u_tpll/ph1p_phy_pll_wrapper_d8cf02616d56_Inst/u_PH1P_PHY_PLL.clkc[2]}]
set_clock_groups -exclusive -group [get_clocks {rx_reclk_e}] -group [get_clocks {rx_reclk_o}]
set_clock_groups -exclusive -group [get_clocks {rx_clk_e_out0}] -group [get_clocks {rx_clk_e_out1}]
set_clock_groups -exclusive -group [get_clocks {rx_clk_o_out0}] -group [get_clocks {rx_clk_o_out1}]
set_clock_groups -exclusive -group [get_clocks {rx_clk_e_out1}] -group [get_clocks {rx_clk_o_out0}]
set_clock_groups -exclusive -group [get_clocks {rx_clk_e_out1}] -group [get_clocks {rx_clk_o_out1}]
set_clock_groups -exclusive -group [get_clocks {rx_clk_e_out0}] -group [get_clocks {rx_clk_o_out0}]
set_clock_groups -exclusive -group [get_clocks {rx_clk_e_out0}] -group [get_clocks {rx_clk_o_out1}]
set_clock_groups -exclusive -group [get_clocks {rx_reclk_e}] -group [get_clocks {rx_reclk_o}]
set_clock_groups -exclusive -group [get_clocks {tx_clk_e_out0 tx_clk_o_out0}]
set_clock_groups -exclusive -group [get_clocks {tx_clk_e_out0}] -group [get_clocks {tx_clk_o_out1}]
